#if !defined(__GNUC__) || defined(__clang__)
	#if defined(__EMSCRIPTEN__)
#pragma message("This source file was transformed for Gcc, but it seems you are attempting to compile it with Emcc. That could be the cause of errors or other unexpected results. It is intended that the compiler used to compile the source be the same as that specified in the --Environment or --Compiler command line options to Tigress.")
	#elif defined(__clang__)
#pragma message("This source file was transformed for Gcc, but it seems you are attempting to compile it with Clang. That could be the cause of errors or other unexpected results. It is intended that the compiler used to compile the source be the same as that specified in the --Environment or --Compiler command line options to Tigress.")
	#elif defined(_MSC_VER)
#pragma message("This source file was transformed for Gcc, but it seems you are attempting to compile it with Msvc. That could be the cause of errors or other unexpected results. It is intended that the compiler used to compile the source be the same as that specified in the --Environment or --Compiler command line options to Tigress.")
	#else
#pragma message("This source file was transformed for Gcc, but it seems you are attempting to compile it with some other compiler. That could be the cause of errors or other unexpected results. It is intended that the compiler used to compile the source be the same as that specified in the --Environment or --Compiler command line options to Tigress.")
	#endif
#endif


/*
BEGIN-TIGRESS
{
  "Tigress": {
    "Source": "This file was generated by Tigress, a product of the University of Arizona.",
    "Author": "Christian Collberg",
    "Contact": "collberg@gmail.com",
    "Version": "4.0.11,Operating system=Linux, Architecture=x86_64, Git hash=b27316009b56c6a9243055163d440e9ae74b2991, Date=2025-07-23T23:33:20:+0000",
    "Url": "https://tigress.wtf"
  },
  "Usage": {
    "Research": "Tigress is free to use for research purposes.",
    "Commercial": "Any use in a commercial setting requires a license from the University of Arizona."
  }
}
END-TIGRESS
*/


/*
BEGIN-CONFIG
[
  {
    "Environment": {
      "architecture": "x86",
      "wordsize": "64",
      "os": "Linux",
      "compiler": "Gcc",
      "compilerVersion": "(5,1)"
    }
  },
  {
    "Major version number": -1,
    "Minor version number": -1,
    "gcc version string": "Unknown",
    "If assembly names have leading underscore": false,
    "Size of 'short'": 2,
    "Size of 'int'": 4,
    "Size of '_Bool'": 1,
    "Size of 'long'": 8,
    "Size of 'long long'": 8,
    "Size of pointers": 8,
    "Size of 'float'": 4,
    "Size of '_Float32x'": 8,
    "Size of '_Float64x'": 16,
    "Size of 'double'": 8,
    "Size of 'long double'": 16,
    "Size of '_Float16'": 0,
    "Size of '_Float128'": 16,
    "Size of 'float _Complex'": 8,
    "Size of 'double _Complex'": 16,
    "Size of 'long double _Complex'": 32,
    "Size of '_Float128 _Complex'": 0,
    "Size of 'void'": 1,
    "Size of function": 8,
    "Type of 'sizeof(T)'": "unsigned long",
    "Type of 'wchar_t'": "int",
    "Type of 'char16_t'": "unsigned short",
    "Type of 'char32_t'": "unsigned int",
    "Alignment of 'short'": 2,
    "Alignment of 'int'": 4,
    "Alignment of '_Bool'": 1,
    "Alignment of 'long'": 8,
    "Alignment of 'long long'": 8,
    "Alignment of pointers": 8,
    "Alignment of enum types": 4,
    "Alignment of 'float'": 4,
    "Alignment of '_Float32x'": 8,
    "Alignment of '_Float64x'": 16,
    "Alignment of 'double'": 8,
    "Alignment of 'long double'": 16,
    "Alignment of '_Float16'": 0,
    "Alignment of '_Float128'": 16,
    "Alignment of 'float _Complex'": 4,
    "Alignment of 'double _Complex'": 8,
    "Alignment of 'long double _Complex'": 16,
    "Alignment of '_Float128 _Complex'": 0,
    "Alignment of strings": 1,
    "Alignment of function": 1,
    "Alignment of anything with the 'aligned' attribute": 16,
    "Whether 'char' is unsigned": false,
    "whether the machine is little endian": true,
    "whether __thread is a keyword": true,
    "whether __builtin_va_list is builtin (gccism)": true
  },
  {
    "C language specification": "C99",
    "Generate code for Microsoct MSVC": false,
    "Whether to convert local static variables into global static variables": false,
    "Whether to use the logical operands LAnd and LOr": false,
    "Whether to use GCC's computed gotos": true,
    "Whether to expand ranges of values in case statements": false
  },
  {
    "Bitsize of char": 8,
    "Bitsize of signed char": 8,
    "Bitsize of unsigned char": 8,
    "Bitsize of _Bool": 8,
    "Bitsize of short": 16,
    "Bitsize of unsigned short": 16,
    "Bitsize of int": 32,
    "Bitsize of unsigned int": 32,
    "Bitsize of long": 64,
    "Bitsize of unsigned long": 64,
    "Bitsize of long long": 64,
    "Bitsize of unsigned long long": 64,
    "Bitsize of __int128": 128,
    "Bitsize of unsigned __int128": 128,
    "Bitsize of float": 32,
    "Bitsize of double": 64,
    "Bitsize of long double": 128,
    "Bitsize of float16": 0,
    "Bitsize of float128": 128,
    "Bitsize of float _Complex": 64,
    "Bitsize of double _Complex": 128,
    "Bitsize of long double _Complex": 256,
    "Bitsize of _float128 _Complex": 0
  }
]
END-CONFIG
*/


/*
BEGIN-OPTIONS
[
  {
    "task": 1,
    "kind": "Flatten",
    "prefix": "",
    "seed": "",
    "funSpec": [ [ "id(main)", "" ] ],
    "globalVarSpec": [],
    "localVarSpec": [],
    "exclude": [],
    "funs": [ "main" ],
    "options": {
      "common": {
        "prefix": "",
        "verbosity": "None",
        "statistics": "None",
        "transformationKind": "Ident",
        "vlaTransformation": "alloca",
        "transformationNumber": "0"
      },
      "kinds": [ "array" ],
      "dispatchKinds": [ "switch" ],
      "obfuscateNext": "false",
      "splitBasicBlocks": "false",
      "randomizeBlocks": "false",
      "dumpBlocks": "false",
      "trace": [],
      "obfuscateEntryPoint": "false",
      "conditionalKinds": [ "branch" ],
      "implicitFlow": "false",
      "implicitFlowOptions": "None",
      "numberOfBlocksPerFunction": "1",
      "splitName": "FLATTEN_SPLIT",
      "implicitFlowOptions": {
        "common": {
          "prefix": "",
          "verbosity": "None",
          "statistics": "None",
          "transformationKind": "Ident",
          "vlaTransformation": "alloca",
          "transformationNumber": "0"
        },
        "handlerCount": "1",
        "jitCount": "1",
        "jitFunctionBody": "(for (for (for (for (if (bb 2) (bb 2))))))",
        "kinds": [ "counter_int" ],
        "combiner": "*",
        "trainingKind": "gap",
        "time": "false",
        "trace": "false",
        "train": "false",
        "trainingTimesClock": "0",
        "trainingTimesThread": "0",
        "trainingMaxFailureRateClock": "5",
        "trainingMaxFailureRateThread": "1",
        "trainingMinGap": "80",
        "trainingData": "None",
        "trainingConfidenceLevel": "0.95",
        "trainingTargetErrorRate": "0.0001",
        "trainingParameterRange": [
          "(trivial_clock,(1,10000))", "(trivial_thread_1,(1,10000))",
          "(trivial_thread_2,(1,10000))", "(trivial_counter,(1,10000))",
          "(file_cache_time,(1,1024))", "(file_cache_thread_1,(1,1024))",
          "(file_cache_thread_2,(1,1024))",
          "(file_cache_thread_timer,(1,1024))", "(mem_cache_time,(2,64))",
          "(mem_cache_thread_1,(2,64))", "(mem_cache_thread_2,(2,64))",
          "(jit_time,(0,0))", "(jit_thread_1,(0,0))", "(jit_thread_2,(0,0))",
          "(jit_thread_timer,(0,0))", "(branchPrediction_time,(2,10))"
        ]
      }
    }
  }
]
END-OPTIONS
*/


/*
BEGIN-UNIVERSE
{
  "Not added to universe": [
    "__sync_fetch_and_xor_2", "__sync_nand_and_fetch_1",
    "__sync_and_and_fetch", "__sync_val_compare_and_swap_16",
    "__atomic_or_fetch", "__sync_sub_and_fetch_1", "__atomic_fetch_and",
    "__atomic_xor_fetch_16", "__atomic_fetch_nand_16",
    "__sync_add_and_fetch_4", "__sync_and_and_fetch_8",
    "__sync_fetch_and_add_2", "__sync_synchronize", "__sync_or_and_fetch",
    "__atomic_xor_fetch_8", "__atomic_xor_fetch_2", "__sync_fetch_and_and_8",
    "__atomic_store_16", "__atomic_fetch_and_8", "__sync_sub_and_fetch_2",
    "__atomic_and_fetch_2", "__atomic_fetch_add_8",
    "__c11_atomic_thread_fence", "__atomic_fetch_nand", "__atomic_store",
    "__atomic_add_fetch_2", "__sync_fetch_and_or_2", "__sync_sub_and_fetch",
    "__sync_fetch_and_add_1", "__sync_and_and_fetch_1",
    "__atomic_nand_fetch_16", "__sync_val_compare_and_swap_8",
    "__sync_xor_and_fetch_1", "__atomic_fetch_xor_8",
    "__sync_or_and_fetch_2", "__sync_fetch_and_sub_16",
    "__atomic_exchange_1", "__sync_fetch_and_and_2", "__sync_fetch_and_and",
    "__atomic_feraiseexcept", "__atomic_and_fetch_4", "__atomic_or_fetch_4",
    "__sync_xor_and_fetch_2", "__sync_swap_2", "__atomic_fetch_and_2",
    "__sync_val_compare_and_swap_4", "__sync_lock_release", "__sync_swap",
    "__atomic_fetch_nand_8", "__sync_fetch_and_add_4",
    "__atomic_fetch_nand_2", "__atomic_load_n", "__atomic_exchange_n",
    "__atomic_fetch_or_8", "__sync_lock_release_4", "__sync_fetch_and_max",
    "__atomic_fetch_or_4", "__atomic_load_2", "__atomic_fetch_sub_4",
    "__atomic_compare_exchange_1", "__sync_fetch_and_sub_2", "__atomic_load",
    "__atomic_or_fetch_16", "__atomic_add_fetch_16", "__sync_lock_release_1",
    "__atomic_fetch_add_16", "__sync_fetch_and_and_1",
    "__atomic_compare_exchange_2", "__sync_and_and_fetch_16",
    "__atomic_exchange", "__atomic_sub_fetch_2", "__atomic_fetch_xor_16",
    "__sync_xor_and_fetch_4", "__atomic_fetch_or_16", "__atomic_load_4",
    "__sync_fetch_and_sub_1", "__atomic_store_n", "__sync_fetch_and_sub_8",
    "__sync_fetch_and_or_16", "__sync_lock_test_and_set",
    "__atomic_fetch_and_16", "__sync_lock_test_and_set_2",
    "__atomic_nand_fetch", "__atomic_load_8", "__atomic_xor_fetch_4",
    "__atomic_fetch_sub_2", "__sync_fetch_and_xor_4",
    "__sync_fetch_and_or_1", "__atomic_store_8", "__sync_nand_and_fetch_4",
    "__atomic_or_fetch_2", "__atomic_fetch_xor", "__sync_add_and_fetch_8",
    "__atomic_fetch_xor_4", "__sync_bool_compare_and_swap",
    "__sync_fetch_and_xor_16", "__atomic_and_fetch_1",
    "__sync_lock_release_2", "__atomic_xor_fetch_1",
    "__sync_xor_and_fetch_8", "__warn_memset_zero_len",
    "__sync_fetch_and_xor_8", "__sync_fetch_and_sub", "__atomic_fetch_add_2",
    "__sync_swap_1", "__sync_fetch_and_xor_1", "__sync_fetch_and_add_16",
    "__sync_fetch_and_umin", "__atomic_fetch_sub", "__sync_fetch_and_nand_4",
    "__sync_add_and_fetch_2", "__c11_atomic_signal_fence",
    "__atomic_add_fetch_4", "__sync_fetch_and_min", "__sync_swap_8",
    "__sync_fetch_and_or", "__sync_sub_and_fetch_4",
    "__sync_lock_test_and_set_4", "__sync_or_and_fetch_8",
    "__sync_lock_release_16", "__sync_fetch_and_or_4",
    "__atomic_nand_fetch_8", "__atomic_sub_fetch_1", "__atomic_fetch_or",
    "__sync_fetch_and_nand_16", "__atomic_nand_fetch_4",
    "__sync_lock_release_8", "__sync_bool_compare_and_swap_1",
    "__atomic_sub_fetch_4", "__atomic_compare_exchange_n",
    "__sync_add_and_fetch", "__atomic_signal_fence", "__atomic_fetch_nand_1",
    "__atomic_and_fetch_16", "__sync_fetch_and_nand",
    "__atomic_thread_fence", "__sync_swap_4", "__atomic_test_and_set",
    "__sync_fetch_and_sub_4", "__atomic_exchange_16", "__xray_customevent",
    "__atomic_clear", "__atomic_fetch_xor_1", "__atomic_and_fetch",
    "__atomic_compare_exchange_4", "__sync_fetch_and_add_8",
    "__sync_or_and_fetch_16", "__sync_nand_and_fetch", "__atomic_load_16",
    "__atomic_always_lock_free", "__sync_xor_and_fetch",
    "__atomic_exchange_8", "__sync_xor_and_fetch_16", "__atomic_or_fetch_8",
    "__sync_add_and_fetch_1", "__sync_bool_compare_and_swap_2",
    "__atomic_or_fetch_1", "__sync_fetch_and_nand_8", "__atomic_fetch_add",
    "__atomic_nand_fetch_1", "__sync_bool_compare_and_swap_16",
    "__atomic_compare_exchange_16", "__atomic_fetch_or_1",
    "__atomic_fetch_add_1", "__c11_atomic_is_lock_free", "__xray_typedevent",
    "__sync_swap_16", "__atomic_fetch_sub_1", "__atomic_store_2",
    "__sync_sub_and_fetch_16", "__sync_fetch_and_nand_1",
    "__atomic_exchange_4", "__sync_fetch_and_nand_2",
    "__sync_nand_and_fetch_2", "__sync_fetch_and_xor",
    "__atomic_fetch_and_4", "__sync_or_and_fetch_1",
    "__atomic_compare_exchange", "__sync_or_and_fetch_4",
    "__sync_lock_test_and_set_16", "__atomic_load_1",
    "__sync_bool_compare_and_swap_8", "__atomic_fetch_xor_2",
    "__sync_val_compare_and_swap", "__atomic_store_4",
    "__atomic_fetch_and_1", "__atomic_fetch_nand_4",
    "__sync_sub_and_fetch_8", "__atomic_sub_fetch_8",
    "__atomic_fetch_sub_16", "__sync_bool_compare_and_swap_4",
    "__sync_val_compare_and_swap_2", "__sync_and_and_fetch_4",
    "__sync_lock_test_and_set_8", "__atomic_exchange_2",
    "__sync_fetch_and_or_8", "__sync_nand_and_fetch_16",
    "__atomic_fetch_add_4", "__atomic_nand_fetch_2", "__atomic_sub_fetch",
    "__sync_lock_test_and_set_1", "__atomic_compare_exchange_8",
    "__atomic_add_fetch", "__atomic_xor_fetch", "__sync_fetch_and_add",
    "__sync_and_and_fetch_2", "__atomic_add_fetch_1", "__atomic_add_fetch_8",
    "__sync_fetch_and_and_4", "__atomic_fetch_sub_8",
    "__sync_fetch_and_and_16", "__sync_val_compare_and_swap_1",
    "__atomic_store_1", "__atomic_fetch_or_2", "__atomic_sub_fetch_16",
    "__sync_add_and_fetch_16", "__sync_nand_and_fetch_8",
    "__atomic_is_lock_free", "__sync_fetch_and_umax", "__atomic_and_fetch_8"
  ],
  "Transformations": [
    {
      "TransformationNumber": 200,
      "TransformationKind": "PlatformFixes",
      "TransformationUpdates": {}
    },
    {
      "TransformationNumber": 1,
      "TransformationKind": "Flatten",
      "TransformationUpdates": {
        "Modified Function Implementations": [ "main" ]
      }
    },
    {
      "TransformationNumber": 0,
      "TransformationKind": "Initialize",
      "TransformationUpdates": {
        "Modified Function Implementations": [ "main" ],
        "New Global Variables": {
          "_TIG_IZ_eB00_envp": "INIT_FUN: '_TIG_IZ_eB00_envp__INIT'",
          "_TIG_IZ_eB00_argv": "INIT_FUN: '_TIG_IZ_eB00_argv__INIT'",
          "_TIG_IZ_eB00_argc": "INIT_FUN: '_TIG_IZ_eB00_argc__INIT'"
        }
      }
    },
    {
      "TransformationNumber": -1,
      "TransformationKind": "Initialize",
      "TransformationUpdates": {
        "New Functions": [ "main" ],
        "New Externs": [
          "__builtin_catanhf", "__builtin_ia32_psrawi",
          "__builtin_rotateright8", "__builtin_fdimf128", "__builtin_log1pf",
          "__builtin_ia32_vec_init_v4hi", "__builtin_isless",
          "__builtin_ia32_paddsw", "__builtin_snprintf",
          "__builtin_ia32_psubd", "__builtin_fmaxf",
          "__builtin_ia32_unpckhps", "__builtin_acos",
          "__builtin_ssubl_overflow", "__builtin___sprintf_chk",
          "__builtin_lgammaf", "__builtin_assume_aligned",
          "__builtin_stpncpy", "__builtin_signbitl", "__builtin_lround",
          "__builtin_rotateleft32", "__builtin_rindex",
          "__builtin_ilogbf128", "__builtin_subc", "__builtin_ia32_pmulhw",
          "__builtin_tanhf", "__builtin_copysignf16", "__builtin_mempcpy",
          "__builtin_subcs", "__builtin_strrchr", "__builtin_fprintf",
          "__builtin_ia32_pand", "__builtin_ctanhl", "__builtin_ia32_pslldi",
          "__builtin_sub_overflow", "__builtin_acoshf128", "__builtin_cpowf",
          "__builtin_sqrtl", "__builtin_parity", "__builtin_cosl",
          "__builtin_remainderf", "__builtin_char_memchr",
          "__builtin_ia32_psrlq", "__builtin_acosl", "__builtin_log2l",
          "__builtin_conjl", "__builtin_clz", "__builtin_add_overflow",
          "__builtin_log10", "__builtin___strcat_chk", "__builtin_cprojl",
          "__builtin_copysignf", "__builtin_modff", "__builtin_realloc",
          "__builtin_logf16", "__builtin_expm1f128", "__builtin_nanf128",
          "__builtin_cacoshl", "__builtin_frexp", "__builtin_acosf",
          "__builtin_sinhl", "__builtin___stpcpy_chk",
          "__builtin_is_aligned", "__builtin_dwarf_cfa",
          "__builtin_ia32_packuswb", "__builtin_ia32_psraw",
          "__builtin_casinhl", "__builtin_nexttowardl", "__builtin_va_start",
          "__builtin_scalbln", "__builtin_bswap16", "__builtin_wcslen",
          "__builtin_log10f16", "__builtin_init_dwarf_reg_size_table",
          "__builtin_ctz", "__builtin_strpbrk", "__builtin_strcpy",
          "__builtin_next_arg", "__builtin_sinf16",
          "__builtin_umull_overflow", "__builtin_scalbnf128",
          "__builtin_ia32_pandn", "__builtin_log10f", "__builtin_fmodf16",
          "__builtin_csinh", "__builtin_floorf",
          "__builtin_matrix_transpose", "__builtin_ia32_pcmpeqw",
          "__builtin___get_unsafe_stack_top", "__builtin_log2f",
          "__builtin_wmemchr", "__builtin_ia32_subps", "__builtin_scalblnf",
          "__builtin_fmal", "__builtin_ia32_punpckhwd", "__builtin_parityll",
          "__builtin_va_end", "__builtin_bzero", "__builtin_strncmp",
          "__builtin_fminl", "__builtin_ia32_psradi",
          "__builtin_ssubll_overflow", "__builtin_sqrtf16",
          "__builtin_smull_overflow", "__builtin___vsprintf_chk",
          "__builtin_nansf128", "__builtin_lgammal", "__builtin_nans",
          "__builtin_ceilf16", "__builtin_exp", "__builtin_acosf128",
          "__builtin_rintf16", "__builtin_ia32_paddusw", "__builtin_wmemcmp",
          "__builtin_round", "__builtin_hypot", "__builtin_subcb",
          "__builtin___strlcpy_chk", "__builtin_csqrt", "__builtin_powif",
          "__builtin_log10l", "__builtin_log10f128", "__builtin_erff128",
          "__builtin_addcl", "__builtin_return_address", "__builtin_fabsf",
          "__builtin_ctanh", "__builtin_ctan", "__builtin_cbrtf128",
          "__builtin_atanhf", "__builtin_ia32_paddusb128", "__builtin_free",
          "__builtin_object_size", "__builtin_va_arg_pack_len",
          "__builtin_tanl", "__builtin_shufflevector", "__builtin_csinhl",
          "__builtin_stpcpy", "__builtin_eh_return_data_regno",
          "__builtin_cexpl", "__builtin_sinl", "__builtin_uaddll_overflow",
          "__builtin_rotateleft16", "__builtin_powf16",
          "__builtin_convertvector", "__builtin_sinhf", "__builtin_hypotl",
          "__builtin_ia32_stmxcsr", "__builtin_bswap64",
          "__builtin_objc_memmove_collectable", "__builtin_ia32_mulps",
          "__builtin_tan", "__builtin_llabs", "__builtin_inff",
          "__builtin_umul_overflow", "__builtin_fmax", "__builtin_erf",
          "__builtin_clzl", "__builtin_ia32_paddq", "__builtin_cosf16",
          "__builtin_tgammal", "__builtin_atan", "__builtin___fprintf_chk",
          "__builtin_wmemcpy", "__builtin_llrintf128", "__builtin_casin",
          "__builtin_logbf128", "__builtin_ctanf", "__builtin_ffsll",
          "__builtin_ia32_pshufw", "__builtin_logf128", "__builtin_index",
          "__builtin_ccosl", "__builtin_abort", "__builtin_powi",
          "__builtin_canonicalize", "__builtin_ia32_psllqi",
          "__builtin_strchr", "__builtin_logb", "__builtin_expf128",
          "__builtin_cimagf", "__builtin_creall", "__builtin_atanh",
          "__builtin_frexpl", "__builtin_exp2f128", "__builtin_csinf",
          "__builtin_ia32_psubusb", "__builtin_ia32_paddsb",
          "__builtin_creal", "__builtin_logl", "__builtin_remquo",
          "__builtin_fmaxl", "__builtin_ia32_cvtsi642ss",
          "__builtin_prefetch", "__builtin_nansl", "__builtin_erfc",
          "__builtin_ccoshl", "__builtin_ia32_emms", "__builtin_tanh",
          "__builtin_scalblnf128", "__builtin_ia32_psubusw128",
          "__builtin_unreachable", "__builtin_calloc", "__builtin_copysignl",
          "__builtin_llrint", "__builtin_ceil", "__builtin_usub_overflow",
          "__builtin_os_log_format", "__builtin_cproj",
          "__builtin_ia32_packssdw", "__builtin_powil",
          "__builtin_ia32_vec_init_v8qi", "__builtin_expl",
          "__builtin_memchr", "__builtin_ia32_cvttss2si64",
          "__builtin_copysign", "__builtin_addcb", "__builtin_logf",
          "__builtin_operator_delete", "__builtin_isunordered",
          "__builtin_casinf", "__builtin_ia32_cvtss2si64",
          "__builtin_ia32_paddusw128", "__builtin_os_log_format_buffer_size",
          "__builtin_memmove", "__builtin_fmaf", "__builtin_debugtrap",
          "__builtin_dynamic_object_size", "__builtin_ffs",
          "__builtin_usubl_overflow", "__builtin_addcs", "__builtin_cargl",
          "__builtin_tgammaf128", "__builtin_launder",
          "__builtin___memcpy_chk", "__builtin_cpowl",
          "__builtin_remainderf128", "__builtin_ssub_overflow",
          "__builtin_tgamma", "__builtin_matrix_column_major_store",
          "__builtin_strspn", "__builtin_conj", "__builtin_cprojf",
          "__builtin_canonicalizef", "__builtin_lrintl", "__builtin_fmaxf16",
          "__builtin_nan", "__builtin_strstr", "__builtin_expm1f",
          "__builtin___get_unsafe_stack_bottom", "__builtin_ia32_pcmpeqb",
          "__builtin_isnormal", "__builtin_atanl", "__builtin_wcsncmp",
          "__builtin_huge_valf128", "__builtin_clzll", "__builtin_cbrt",
          "__builtin_huge_valf", "__builtin_uadd_overflow",
          "__builtin_copysignf128", "__builtin_truncl",
          "__builtin___stpncpy_chk", "__builtin_ia32_punpckhbw",
          "__builtin_ia32_vec_init_v2si", "__builtin_roundf",
          "__builtin_cimag", "__builtin_ia32_pmaddwd",
          "__builtin___vsnprintf_chk", "__builtin_scalbn",
          "__builtin_lgammaf128", "__builtin_ia32_pcmpgtd", "__builtin_nanf",
          "__builtin_roundl", "__builtin_remainderl",
          "__builtin_saddl_overflow", "__builtin_ceilf128",
          "__builtin_signbitf", "__builtin_tgmath", "__builtin_ceill",
          "__builtin_smul_overflow", "__builtin_cabsl",
          "__builtin_ia32_psrad", "__builtin_fmin", "__builtin_floor",
          "__builtin_scalblnl", "__builtin_atan2f", "__builtin_cacosh",
          "__builtin___strlcat_chk", "__builtin_sinh", "__builtin_ilogbf",
          "__builtin_catanl", "__builtin_ia32_psubsw128", "__builtin_clzs",
          "__builtin_remquof", "__builtin_logbf", "__builtin_fma",
          "__builtin_asinhf128", "__builtin_infl", "__builtin_fminf128",
          "__builtin_bitreverse64", "__builtin_vsprintf",
          "__builtin_remquof128", "__builtin_atanhf128",
          "__builtin___get_unsafe_stack_ptr", "__builtin_signbit",
          "__builtin_lroundf", "__builtin_islessequal", "__builtin_exp2l",
          "__builtin_frame_address", "__builtin_nexttowardf128",
          "__builtin_isinf_sign", "__builtin_inff128", "__builtin_va_copy",
          "__builtin_erfcl", "__builtin_cacosf",
          "__builtin_frob_return_address", "__builtin_vsnprintf",
          "__builtin_sadd_overflow", "__builtin_tanf128",
          "__builtin_rotateleft64", "__builtin_matrix_column_major_load",
          "__builtin_popcountll", "__builtin_nearbyintf", "__builtin_atanf",
          "__builtin_rint", "__builtin_ia32_addps",
          "__builtin_rotateright64", "__builtin_readcyclecounter",
          "__builtin_llroundf", "__builtin_strcspn", "__builtin_asinf",
          "__builtin_lrint", "__builtin_erff", "__builtin_ia32_maxps",
          "__builtin_bcmp", "__builtin_asinf128", "__builtin_rotateleft8",
          "__builtin_ia32_por", "__builtin_nextafterf128", "__builtin_cosh",
          "__builtin_tgammaf", "__builtin_operator_new", "__builtin_crealf",
          "__builtin_longjmp", "__builtin_nextafterf",
          "__builtin_mul_overflow", "__builtin_ia32_psrlwi",
          "__builtin_coshl", "__builtin_ilogb",
          "__builtin_ia32_vec_ext_v8hi", "__builtin_cosf",
          "__builtin_strndup", "__builtin_cpow", "__builtin___mempcpy_chk",
          "__builtin_llrintf", "__builtin_hypotf128", "__builtin_complex",
          "__builtin_remainder", "__builtin_preserve_access_index",
          "__builtin_fmaf128", "__builtin_acosh", "__builtin_sin",
          "__builtin_llround", "__builtin_fabs", "__builtin_trunc",
          "__builtin_fmaxf128", "__builtin_ccosf", "__builtin_acoshl",
          "__builtin___clear_cache", "__builtin_strncasecmp",
          "__builtin_fdiml", "__builtin_ia32_paddw", "__builtin_sinhf128",
          "__builtin_isnan", "__builtin_fdim", "__builtin_isgreaterequal",
          "__builtin_nexttowardf", "__builtin_fminf16",
          "__builtin_ia32_packsswb", "__builtin_sqrt",
          "__builtin_umulll_overflow", "__builtin_floorf16",
          "__builtin_casinh", "__builtin_llrintl", "__builtin_expm1",
          "__builtin_exp2f", "__builtin_fabsl", "__builtin_setjmp",
          "__builtin_nearbyintl", "__builtin_nearbyintf128",
          "__builtin_lrintf", "__builtin_floorl", "__builtin_carg",
          "__builtin_csin", "__builtin_clogl",
          "__builtin_expect_with_probability", "__builtin_erfl",
          "__builtin_asinhl", "__builtin_memcpy", "__builtin_islessgreater",
          "__builtin_ia32_psrlqi", "__builtin_ia32_psubsb",
          "__builtin_ctanhf", "__builtin_wcscmp",
          "__builtin_ia32_psubusb128", "__builtin_bitreverse16",
          "__builtin_classify_type", "__builtin_cacos", "__builtin_lroundl",
          "__builtin_printf", "__builtin_sqrtf", "__builtin_assume",
          "__builtin_rintf", "__builtin_powf", "__builtin_powl",
          "__builtin_cimagl", "__builtin_addcll", "__builtin_ia32_psrlw",
          "__builtin_ia32_pslld", "__builtin_canonicalizef16",
          "__builtin___memccpy_chk", "__builtin_truncf128",
          "__builtin_nextafter", "__builtin_ia32_pxor", "__builtin_strdup",
          "__builtin_fabsf16", "__builtin_strcmp", "__builtin_atanf128",
          "__builtin_ia32_psubsb128", "__builtin_ia32_paddsw128",
          "__builtin_ldexpf", "__builtin_ia32_psrld", "__builtin_truncf16",
          "__builtin___memmove_chk", "__builtin_modff128",
          "__builtin_isfinite", "__builtin_conjf", "__builtin_roundf128",
          "__builtin_powf128", "__builtin_ctzs", "__builtin_roundf16",
          "__builtin_ia32_pcmpgtb", "__builtin_log1pf128",
          "__builtin_rotateright16", "__builtin_alloca",
          "__builtin_ldexpf128", "__builtin_cbrtl", "__builtin_csinhf",
          "__builtin_log2", "__builtin_ia32_paddd", "__builtin_modfl",
          "__builtin_ccos", "__builtin_casinhf", "__builtin_asin",
          "__builtin_erfcf128", "__builtin_clrsbll", "__builtin_ctzl",
          "__builtin_tanhl", "__builtin_saddll_overflow", "__builtin_labs",
          "__builtin_cabsf", "__builtin_ia32_punpckhdq",
          "__builtin_ia32_psubb", "__builtin_rintf128", "__builtin_fdimf",
          "__builtin_ia32_vec_ext_v2si", "__builtin_alloca_with_align",
          "__builtin_wmemmove", "__builtin_ia32_psubsw", "__builtin_strncpy",
          "__builtin_eh_return", "__builtin___memset_chk",
          "__builtin_scalbnf", "__builtin_fpclassify", "__builtin_huge_val",
          "__builtin_ia32_pcmpeqd", "__builtin_frexpf", "__builtin_wcschr",
          "__builtin_truncf", "__builtin_ia32_paddusb",
          "__builtin_canonicalizel", "__builtin_ia32_pcmpgtw",
          "__builtin_fmodl", "__builtin_isinf", "__builtin_ia32_psubq",
          "__builtin_strcat", "__builtin_ilogbl", "__builtin_bitreverse32",
          "__builtin_ceilf", "__builtin_dump_struct", "__builtin_return",
          "__builtin_asinl", "__builtin_frexpf128", "__builtin_ia32_psllwi",
          "__builtin_bitreverse8", "__builtin_va_arg_pack",
          "__builtin___strncpy_chk", "__builtin_nontemporal_store",
          "__builtin_lrintf128", "__builtin_malloc", "__builtin_atanhl",
          "__builtin_uaddl_overflow", "__builtin___strncat_chk",
          "__builtin_flt_rounds", "__builtin_huge_vall", "__builtin_ffsl",
          "__builtin___vprintf_chk", "__builtin_rintl", "__builtin_erfcf",
          "__builtin_ia32_unpcklps", "__builtin_strncat", "__builtin_ctzll",
          "__builtin_stdarg_start", "__builtin_nontemporal_load",
          "__builtin_cbrtf", "__builtin_ia32_pmullw", "__builtin_catan",
          "__builtin_ia32_punpcklbw", "__builtin_nexttoward",
          "__builtin_tanf", "__builtin_rotateright32", "__builtin_exp2",
          "__builtin_log1p", "__builtin_catanf", "__builtin_va_arg",
          "__builtin_expect", "__builtin_subcl", "__builtin_ia32_paddsb128",
          "__builtin___printf_chk", "__builtin_subcll",
          "__builtin___vfprintf_chk", "__builtin_fmod",
          "__builtin_ia32_paddb", "__builtin_call_with_static_chain",
          "__builtin_align_up", "__builtin_lgamma", "__builtin_ccosh",
          "__builtin_sqrtf128", "__builtin_ia32_vec_set_v8hi",
          "__builtin_ldexpl", "__builtin_usubll_overflow",
          "__builtin_sprintf", "__builtin_nearbyint", "__builtin_apply",
          "__builtin_sinf", "__builtin_logbl", "__builtin_log1pl",
          "__builtin_ia32_punpcklwd", "__builtin_asinh",
          "__builtin_constant_p", "__builtin_memcpy_inline",
          "__builtin_fminf", "__builtin_llroundl", "__builtin_csinl",
          "__builtin_ia32_punpckldq", "__builtin_log", "__builtin_expf",
          "__builtin_exp2f16", "__builtin_types_compatible_p",
          "__builtin_atan2l", "__builtin_apply_args", "__builtin_clrsb",
          "__builtin_catanhl", "__builtin___get_unsafe_stack_start",
          "__builtin_ia32_psubusw", "__builtin_llroundf128",
          "__builtin_ctanl", "__builtin_abs", "__builtin_log2f128",
          "__builtin_clogf", "__builtin_strlen", "__builtin_ia32_psubw",
          "__builtin_inf", "__builtin_cosf128", "__builtin_remquol",
          "__builtin_fmaf16", "__builtin_coshf128", "__builtin_cargf",
          "__builtin_acoshf", "__builtin_cacoshf", "__builtin_ia32_psllq",
          "__builtin_trap", "__builtin_smulll_overflow", "__builtin_parityl",
          "__builtin_cacosl", "__builtin_log2f16", "__builtin_annotation",
          "__builtin_clog", "__builtin_varargs_start", "__builtin_fabsf128",
          "__builtin_cexpf", "__builtin_unwind_init", "__builtin_isgreater",
          "__builtin___snprintf_chk", "__builtin_ia32_vec_ext_v4hi",
          "__builtin_cabs", "__builtin_expm1l", "__builtin_coshf",
          "__builtin_casinl", "__builtin_nansf", "__builtin_strcasecmp",
          "__builtin_hypotf", "__builtin_nextafterl", "__builtin_lroundf128",
          "__builtin_csqrtf", "__builtin_catanh", "__builtin_align_down",
          "__builtin_scalbnl", "__builtin_ia32_vec_set_v4hi",
          "__builtin_csqrtl", "__builtin_sinf128", "__builtin_atan2",
          "__builtin_popcountl", "__builtin_ia32_psllw",
          "__builtin___strcpy_chk", "__builtin_atan2f128",
          "__builtin_thread_pointer", "__builtin_addc", "__builtin_cos",
          "__builtin_cexp", "__builtin_memset", "__builtin_nanl",
          "__builtin_popcount", "__builtin_tanhf128", "__builtin_expf16",
          "__builtin_dwarf_sp_column", "__builtin_bcopy", "__builtin_memcmp",
          "__builtin_ccoshf", "__builtin_clrsbl", "__builtin_asinhf",
          "__builtin_floorf128", "__builtin_extend_pointer",
          "__builtin_ia32_ldmxcsr", "__builtin_extract_return_addr",
          "__builtin_bswap32", "__builtin_ldexp", "__builtin_unpredictable",
          "__builtin_fmodf", "__builtin_fmodf128", "__builtin_ia32_psrldi",
          "stdin", "stdout", "stderr", "remove", "rename", "renameat",
          "fclose", "tmpfile", "tmpnam", "tmpnam_r", "tempnam", "fflush",
          "fflush_unlocked", "fopen", "freopen", "fdopen", "fopencookie",
          "fmemopen", "open_memstream", "setbuf", "setvbuf", "setbuffer",
          "setlinebuf", "fprintf", "printf", "sprintf", "vfprintf",
          "vprintf", "vsprintf", "snprintf", "vsnprintf", "vasprintf",
          "__asprintf", "asprintf", "vdprintf", "dprintf", "fscanf", "scanf",
          "sscanf", "vfscanf", "vscanf", "vsscanf", "fgetc", "getc",
          "getchar", "getc_unlocked", "getchar_unlocked", "fgetc_unlocked",
          "fputc", "putc", "putchar", "fputc_unlocked", "putc_unlocked",
          "putchar_unlocked", "getw", "putw", "fgets", "__getdelim",
          "getdelim", "getline", "fputs", "puts", "ungetc", "fread",
          "fwrite", "fread_unlocked", "fwrite_unlocked", "fseek", "ftell",
          "rewind", "fseeko", "ftello", "fgetpos", "fsetpos", "clearerr",
          "feof", "ferror", "clearerr_unlocked", "feof_unlocked",
          "ferror_unlocked", "perror", "fileno", "fileno_unlocked", "pclose",
          "popen", "ctermid", "flockfile", "ftrylockfile", "funlockfile",
          "__uflow", "__overflow"
        ],
        "New Types": [
          "fpos_t", "ssize_t", "off_t", "va_list", "cookie_io_functions_t",
          "_IO_cookie_io_functions_t", "cookie_close_function_t",
          "cookie_seek_function_t", "cookie_write_function_t",
          "cookie_read_function_t", "_IO_FILE", "_IO_lock_t",
          "_IO_wide_data", "_IO_codecvt", "_IO_marker", "FILE", "__FILE",
          "_IO_FILE", "__fpos64_t", "_G_fpos64_t", "__fpos_t", "_G_fpos_t",
          "__mbstate_t", "__anonstruct___mbstate_t_599531343",
          "__anonunion___value_751190509", "__sig_atomic_t", "__socklen_t",
          "__intptr_t", "__caddr_t", "__loff_t", "__syscall_ulong_t",
          "__syscall_slong_t", "__ssize_t", "__fsword_t", "__fsfilcnt64_t",
          "__fsfilcnt_t", "__fsblkcnt64_t", "__fsblkcnt_t", "__blkcnt64_t",
          "__blkcnt_t", "__blksize_t", "__timer_t", "__clockid_t", "__key_t",
          "__daddr_t", "__suseconds64_t", "__suseconds_t", "__useconds_t",
          "__time_t", "__id_t", "__rlim64_t", "__rlim_t", "__clock_t",
          "__fsid_t", "__anonstruct___fsid_t_109580352", "__pid_t",
          "__off64_t", "__off_t", "__nlink_t", "__mode_t", "__ino64_t",
          "__ino_t", "__gid_t", "__uid_t", "__dev_t", "__uintmax_t",
          "__intmax_t", "__u_quad_t", "__quad_t", "__uint_least64_t",
          "__int_least64_t", "__uint_least32_t", "__int_least32_t",
          "__uint_least16_t", "__int_least16_t", "__uint_least8_t",
          "__int_least8_t", "__uint64_t", "__int64_t", "__uint32_t",
          "__int32_t", "__uint16_t", "__int16_t", "__uint8_t", "__int8_t",
          "__u_long", "__u_int", "__u_short", "__u_char", "__gnuc_va_list",
          "size_t"
        ]
      }
    }
  ]
}
END-UNIVERSE
*/


/* BEGIN TYPEDEF __fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h"
typedef struct _G_fpos_t __fpos_t;
/* END TYPEDEF __fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 */

/* BEGIN TYPEDEF FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/FILE.h:7 */
#line 7 "/usr/include/x86_64-linux-gnu/bits/types/FILE.h"
typedef struct _IO_FILE FILE;
/* END TYPEDEF FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/FILE.h:7 */

/* BEGIN UNION __anonunion___value_751190509 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 CKEY=11 */
#line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
union __anonunion___value_751190509 {
   unsigned int __wch ;
   char __wchb[4] ;
};
/* END UNION __anonunion___value_751190509 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 CKEY=11 */

/* BEGIN TYPEDEF __ssize_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:194 */
#line 194 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __ssize_t;
/* END TYPEDEF __ssize_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:194 */

/* BEGIN TYPEDEF size_t LOC=/usr/lib/gcc/x86_64-linux-gnu/13/include/stddef.h:214 */
#line 214 "/usr/lib/gcc/x86_64-linux-gnu/13/include/stddef.h"
typedef unsigned long size_t;
/* END TYPEDEF size_t LOC=/usr/lib/gcc/x86_64-linux-gnu/13/include/stddef.h:214 */

/* BEGIN TYPEDEF __off64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:153 */
#line 153 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off64_t;
/* END TYPEDEF __off64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:153 */

/* BEGIN TYPEDEF __gnuc_va_list LOC=/usr/lib/gcc/x86_64-linux-gnu/13/include/stdarg.h:40 */
#line 40 "/usr/lib/gcc/x86_64-linux-gnu/13/include/stdarg.h"
typedef __builtin_va_list __gnuc_va_list;
/* END TYPEDEF __gnuc_va_list LOC=/usr/lib/gcc/x86_64-linux-gnu/13/include/stdarg.h:40 */

/* BEGIN FUNCTION-DECL __builtin_free LOC=BUILTIN VKEY=286 */
/* compiler builtin: 
   void __builtin_free(void * ) ;  */
/* END FUNCTION-DECL __builtin_free LOC=BUILTIN VKEY=286 */

/* BEGIN TYPEDEF __off_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:152 */
#line 152 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __off_t;
/* END TYPEDEF __off_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:152 */

/* BEGIN TYPEDEF __uint16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:40 */
#line 40 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned short __uint16_t;
/* END TYPEDEF __uint16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:40 */

/* BEGIN TYPEDEF fpos_t LOC=/usr/include/stdio.h:85 */
#line 85 "/usr/include/stdio.h"
typedef __fpos_t fpos_t;
/* END TYPEDEF fpos_t LOC=/usr/include/stdio.h:85 */

/* BEGIN TYPEDEF __int64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:44 */
#line 44 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __int64_t;
/* END TYPEDEF __int64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:44 */

/* BEGIN FUNCTION-DECL-EXTERN fclose LOC=/usr/include/stdio.h:184 VKEY=1006 */
#line 184 "/usr/include/stdio.h"
extern int ( __attribute__((__nonnull__(1))) fclose)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fclose LOC=/usr/include/stdio.h:184 VKEY=1006 */

/* BEGIN TYPEDEF __uint8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:38 */
#line 38 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned char __uint8_t;
/* END TYPEDEF __uint8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:38 */

/* BEGIN TYPEDEF cookie_io_functions_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:55 */
#line 55 "/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h"
typedef struct _IO_cookie_io_functions_t cookie_io_functions_t;
/* END TYPEDEF cookie_io_functions_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:55 */

/* BEGIN TYPEDEF __uint32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:42 */
#line 42 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __uint32_t;
/* END TYPEDEF __uint32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:42 */

/* BEGIN TYPEDEF __int16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:39 */
#line 39 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef short __int16_t;
/* END TYPEDEF __int16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:39 */

/* BEGIN TYPEDEF __int32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:41 */
#line 41 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __int32_t;
/* END TYPEDEF __int32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:41 */

/* BEGIN TYPEDEF __int8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:37 */
#line 37 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef signed char __int8_t;
/* END TYPEDEF __int8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:37 */

/* BEGIN STRUCT __anonstruct___mbstate_t_599531343 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 10 */
#line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
struct __anonstruct___mbstate_t_599531343 {
   int __count ;
   union __anonunion___value_751190509 __value ;
};
/* END STRUCT __anonstruct___mbstate_t_599531343 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 10 */

/* BEGIN TYPEDEF __mbstate_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 */
#line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
typedef struct __anonstruct___mbstate_t_599531343 __mbstate_t;
/* END TYPEDEF __mbstate_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 */

/* BEGIN FUNCTION-DECL-EXTERN pclose LOC=/usr/include/stdio.h:897 VKEY=1423 */
#line 897 "/usr/include/stdio.h"
extern int ( __attribute__((__nonnull__(1))) pclose)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN pclose LOC=/usr/include/stdio.h:897 VKEY=1423 */

/* BEGIN TYPEDEF __uint64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:45 */
#line 45 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __uint64_t;
/* END TYPEDEF __uint64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:45 */

/* BEGIN TYPEDEF _IO_lock_t LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:43 */
#line 43 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
typedef void _IO_lock_t;
/* END TYPEDEF _IO_lock_t LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:43 */

/* BEGIN TYPEDEF cookie_close_function_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:48 */
#line 48 "/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h"
typedef int cookie_close_function_t(void *__cookie );
/* END TYPEDEF cookie_close_function_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:48 */

/* BEGIN TYPEDEF cookie_read_function_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:27 */
#line 27 "/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h"
typedef __ssize_t cookie_read_function_t(void *__cookie , char *__buf , size_t __nbytes );
/* END TYPEDEF cookie_read_function_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:27 */

/* BEGIN TYPEDEF cookie_seek_function_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:45 */
#line 45 "/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h"
typedef int cookie_seek_function_t(void *__cookie , __off64_t *__pos , int __w );
/* END TYPEDEF cookie_seek_function_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:45 */

/* BEGIN TYPEDEF cookie_write_function_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:36 */
#line 36 "/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h"
typedef __ssize_t cookie_write_function_t(void *__cookie , char const   *__buf , size_t __nbytes );
/* END TYPEDEF cookie_write_function_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:36 */

/* BEGIN VARIABLE-DEF _TIG_IZ_eB00_argv LOC=UNKNOWN VKEY=1466 */
char **_TIG_IZ_eB00_argv  ;
/* END VARIABLE-DEF _TIG_IZ_eB00_argv LOC=UNKNOWN VKEY=1466 */

/* BEGIN TYPEDEF __caddr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:204 */
#line 204 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef char *__caddr_t;
/* END TYPEDEF __caddr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:204 */

/* BEGIN FUNCTION-DECL-EXTERN sscanf LOC=/usr/include/stdio.h:430 VKEY=1176 */
#line 430 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) sscanf)(char const   * __restrict  __s ,
                                                                             char const   * __restrict  __format 
                                                                             , ...)  __asm__("__isoc99_sscanf")  ;
/* END FUNCTION-DECL-EXTERN sscanf LOC=/usr/include/stdio.h:430 VKEY=1176 */

/* BEGIN TYPEDEF ssize_t LOC=/usr/include/stdio.h:78 */
#line 78 "/usr/include/stdio.h"
typedef __ssize_t ssize_t;
/* END TYPEDEF ssize_t LOC=/usr/include/stdio.h:78 */

/* BEGIN TYPEDEF __fsid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 */
#line 155 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef struct __anonstruct___fsid_t_109580352 __fsid_t;
/* END TYPEDEF __fsid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 */

/* BEGIN TYPEDEF __fsword_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:192 */
#line 192 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __fsword_t;
/* END TYPEDEF __fsword_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:192 */

/* BEGIN TYPEDEF __gid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:147 */
#line 147 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __gid_t;
/* END TYPEDEF __gid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:147 */

/* BEGIN TYPEDEF __daddr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:165 */
#line 165 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __daddr_t;
/* END TYPEDEF __daddr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:165 */

/* BEGIN FUNCTION-DECL-EXTERN vfprintf LOC=/usr/include/stdio.h:372 VKEY=1106 */
#line 372 "/usr/include/stdio.h"
extern int ( __attribute__((__nonnull__(1))) vfprintf)(FILE * __restrict  __s , char const   * __restrict  __format ,
                                                       __gnuc_va_list __arg ) ;
/* END FUNCTION-DECL-EXTERN vfprintf LOC=/usr/include/stdio.h:372 VKEY=1106 */

/* BEGIN VARIABLE-DECL _TIG_IZ_eB00_envp LOC=UNKNOWN VKEY=1468 */
char **_TIG_IZ_eB00_envp ;
/* END VARIABLE-DECL _TIG_IZ_eB00_envp LOC=UNKNOWN VKEY=1468 */

/* BEGIN FUNCTION-DECL-EXTERN vasprintf LOC=/usr/include/stdio.h:397 VKEY=1141 */
#line 397
extern  __attribute__((__nothrow__)) int ( /* format attribute */  vasprintf)(char ** __restrict  __ptr ,
                                                                              char const   * __restrict  __f ,
                                                                              __gnuc_va_list __arg ) ;
/* END FUNCTION-DECL-EXTERN vasprintf LOC=/usr/include/stdio.h:397 VKEY=1141 */

/* BEGIN FUNCTION-DECL-EXTERN vsnprintf LOC=/usr/include/stdio.h:389 VKEY=1134 */
#line 389
extern  __attribute__((__nothrow__)) int ( /* format attribute */  vsnprintf)(char * __restrict  __s ,
                                                                              size_t __maxlen ,
                                                                              char const   * __restrict  __format ,
                                                                              __gnuc_va_list __arg ) ;
/* END FUNCTION-DECL-EXTERN vsnprintf LOC=/usr/include/stdio.h:389 VKEY=1134 */

/* BEGIN TYPEDEF __blksize_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:175 */
#line 175 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blksize_t;
/* END TYPEDEF __blksize_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:175 */

/* BEGIN FUNCTION-DECL-EXTERN getchar_unlocked LOC=/usr/include/stdio.h:590 VKEY=1242 */
#line 590 "/usr/include/stdio.h"
extern int getchar_unlocked(void) ;
/* END FUNCTION-DECL-EXTERN getchar_unlocked LOC=/usr/include/stdio.h:590 VKEY=1242 */

/* BEGIN FUNCTION-DECL-EXTERN tempnam LOC=/usr/include/stdio.h:228 VKEY=1020 */
#line 228
extern  __attribute__((__nothrow__)) char *( __attribute__((__leaf__)) tempnam)(char const   *__dir ,
                                                                                char const   *__pfx )  __attribute__((__malloc__(__builtin_free,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN tempnam LOC=/usr/include/stdio.h:228 VKEY=1020 */

/* BEGIN TYPEDEF __mode_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:150 */
#line 150 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __mode_t;
/* END TYPEDEF __mode_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:150 */

/* BEGIN TYPEDEF off_t LOC=/usr/include/stdio.h:64 */
#line 64 "/usr/include/stdio.h"
typedef __off_t off_t;
/* END TYPEDEF off_t LOC=/usr/include/stdio.h:64 */

/* BEGIN TYPEDEF __suseconds64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:163 */
#line 163 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __suseconds64_t;
/* END TYPEDEF __suseconds64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:163 */

/* BEGIN TYPEDEF __uint_least16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:55 */
#line 55 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint16_t __uint_least16_t;
/* END TYPEDEF __uint_least16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:55 */

/* BEGIN FUNCTION-DECL-EXTERN fsetpos LOC=/usr/include/stdio.h:835 VKEY=1393 */
#line 835 "/usr/include/stdio.h"
extern int ( __attribute__((__nonnull__(1))) fsetpos)(FILE *__stream , fpos_t const   *__pos ) ;
/* END FUNCTION-DECL-EXTERN fsetpos LOC=/usr/include/stdio.h:835 VKEY=1393 */

/* BEGIN TYPEDEF __time_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:160 */
#line 160 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __time_t;
/* END TYPEDEF __time_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:160 */

/* BEGIN FUNCTION-DECL-EXTERN fread_unlocked LOC=/usr/include/stdio.h:766 VKEY=1351 */
#line 766 "/usr/include/stdio.h"
extern size_t ( __attribute__((__nonnull__(4))) fread_unlocked)(void * __restrict  __ptr ,
                                                                size_t __size , size_t __n ,
                                                                FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN fread_unlocked LOC=/usr/include/stdio.h:766 VKEY=1351 */

/* BEGIN STRUCT-DECL _IO_wide_data LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:38 17 */
#line 38 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_wide_data ;
/* END STRUCT-DECL _IO_wide_data LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:38 17 */

/* BEGIN FUNCTION-DECL-EXTERN feof LOC=/usr/include/stdio.h:862 VKEY=1399 */
#line 862 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) feof)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN feof LOC=/usr/include/stdio.h:862 VKEY=1399 */

/* BEGIN FUNCTION-DECL-EXTERN putc_unlocked LOC=/usr/include/stdio.h:635 VKEY=1268 */
#line 635
extern int ( __attribute__((__nonnull__(2))) putc_unlocked)(int __c , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN putc_unlocked LOC=/usr/include/stdio.h:635 VKEY=1268 */

/* BEGIN TYPEDEF __int_least64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:58 */
#line 58 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int64_t __int_least64_t;
/* END TYPEDEF __int_least64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:58 */

/* BEGIN TYPEDEF __ino_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:148 */
#line 148 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __ino_t;
/* END TYPEDEF __ino_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:148 */

/* BEGIN FUNCTION-DECL-EXTERN putc LOC=/usr/include/stdio.h:612 VKEY=1255 */
#line 612 "/usr/include/stdio.h"
extern int ( __attribute__((__nonnull__(2))) putc)(int __c , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN putc LOC=/usr/include/stdio.h:612 VKEY=1255 */

/* BEGIN STRUCT-DECL _IO_codecvt LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:37 16 */
#line 37 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_codecvt ;
/* END STRUCT-DECL _IO_codecvt LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:37 16 */

/* BEGIN FUNCTION-DECL-EXTERN tmpfile LOC=/usr/include/stdio.h:194 VKEY=1009 */
#line 194 "/usr/include/stdio.h"
extern FILE *tmpfile(void)  __attribute__((__malloc__(fclose,1), __malloc__)) ;
/* END FUNCTION-DECL-EXTERN tmpfile LOC=/usr/include/stdio.h:194 VKEY=1009 */

/* BEGIN VARIABLE-DECL-EXTERN stdin LOC=/usr/include/stdio.h:149 VKEY=984 */
#line 149
extern FILE *stdin ;
/* END VARIABLE-DECL-EXTERN stdin LOC=/usr/include/stdio.h:149 VKEY=984 */

/* BEGIN VARIABLE-DEF _TIG_IZ_eB00_envp LOC=UNKNOWN VKEY=1468 */
char **_TIG_IZ_eB00_envp  ;
/* END VARIABLE-DEF _TIG_IZ_eB00_envp LOC=UNKNOWN VKEY=1468 */

/* BEGIN FUNCTION-DECL-EXTERN feof_unlocked LOC=/usr/include/stdio.h:869 VKEY=1408 */
#line 869
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) feof_unlocked)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN feof_unlocked LOC=/usr/include/stdio.h:869 VKEY=1408 */

/* BEGIN STRUCT-DECL _G_fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 13 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h"
struct _G_fpos64_t ;
/* END STRUCT-DECL _G_fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 13 */

/* BEGIN TYPEDEF __uint_least8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:53 */
#line 53 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint8_t __uint_least8_t;
/* END TYPEDEF __uint_least8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:53 */

/* BEGIN TYPEDEF __uintmax_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:73 */
#line 73 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __uintmax_t;
/* END TYPEDEF __uintmax_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:73 */

/* BEGIN TYPEDEF __clock_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:156 */
#line 156 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __clock_t;
/* END TYPEDEF __clock_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:156 */

/* BEGIN FUNCTION-DECL-EXTERN open_memstream LOC=/usr/include/stdio.h:320 VKEY=1062 */
#line 320 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) FILE *( __attribute__((__leaf__)) open_memstream)(char **__bufloc ,
                                                                                       size_t *__sizeloc )  __attribute__((__malloc__(fclose,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN open_memstream LOC=/usr/include/stdio.h:320 VKEY=1062 */

/* BEGIN FUNCTION-DECL-EXTERN fopencookie LOC=/usr/include/stdio.h:306 VKEY=1050 */
#line 306
extern  __attribute__((__nothrow__)) FILE *( __attribute__((__leaf__)) fopencookie)(void * __restrict  __magic_cookie ,
                                                                                    char const   * __restrict  __modes ,
                                                                                    cookie_io_functions_t __io_funcs )  __attribute__((__malloc__(fclose,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN fopencookie LOC=/usr/include/stdio.h:306 VKEY=1050 */

/* BEGIN FUNCTION-DECL-EXTERN snprintf LOC=/usr/include/stdio.h:385 VKEY=1125 */
#line 385
extern  __attribute__((__nothrow__)) int ( /* format attribute */  snprintf)(char * __restrict  __s ,
                                                                             size_t __maxlen ,
                                                                             char const   * __restrict  __format 
                                                                             , ...) ;
/* END FUNCTION-DECL-EXTERN snprintf LOC=/usr/include/stdio.h:385 VKEY=1125 */

/* BEGIN FUNCTION-DECL-EXTERN __uflow LOC=/usr/include/stdio.h:959 VKEY=1443 */
#line 959
extern int __uflow(FILE * ) ;
/* END FUNCTION-DECL-EXTERN __uflow LOC=/usr/include/stdio.h:959 VKEY=1443 */

/* BEGIN TYPEDEF __u_short LOC=/usr/include/x86_64-linux-gnu/bits/types.h:32 */
#line 32 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned short __u_short;
/* END TYPEDEF __u_short LOC=/usr/include/x86_64-linux-gnu/bits/types.h:32 */

/* BEGIN FUNCTION-DECL-EXTERN clearerr_unlocked LOC=/usr/include/stdio.h:868 VKEY=1405 */
#line 868 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) void ( __attribute__((__nonnull__(1), __leaf__)) clearerr_unlocked)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN clearerr_unlocked LOC=/usr/include/stdio.h:868 VKEY=1405 */

/* BEGIN TYPEDEF __u_long LOC=/usr/include/x86_64-linux-gnu/bits/types.h:34 */
#line 34 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __u_long;
/* END TYPEDEF __u_long LOC=/usr/include/x86_64-linux-gnu/bits/types.h:34 */

/* BEGIN TYPEDEF __socklen_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:210 */
#line 210 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __socklen_t;
/* END TYPEDEF __socklen_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:210 */

/* BEGIN FUNCTION-DECL-EXTERN printf LOC=/usr/include/stdio.h:363 VKEY=1094 */
#line 363 "/usr/include/stdio.h"
extern int printf(char const   * __restrict  __format  , ...) ;
/* END FUNCTION-DECL-EXTERN printf LOC=/usr/include/stdio.h:363 VKEY=1094 */

/* BEGIN STRUCT-DECL __anonstruct___fsid_t_109580352 LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 9 */
#line 155 "/usr/include/x86_64-linux-gnu/bits/types.h"
struct __anonstruct___fsid_t_109580352 ;
/* END STRUCT-DECL __anonstruct___fsid_t_109580352 LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 9 */

/* BEGIN VARIABLE-DECL-EXTERN stderr LOC=/usr/include/stdio.h:151 VKEY=986 */
#line 151 "/usr/include/stdio.h"
extern FILE *stderr ;
/* END VARIABLE-DECL-EXTERN stderr LOC=/usr/include/stdio.h:151 VKEY=986 */

/* BEGIN VARIABLE-DECL _TIG_IZ_eB00_argc LOC=UNKNOWN VKEY=1465 */
int _TIG_IZ_eB00_argc ;
/* END VARIABLE-DECL _TIG_IZ_eB00_argc LOC=UNKNOWN VKEY=1465 */

/* BEGIN TYPEDEF __key_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:166 */
#line 166 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __key_t;
/* END TYPEDEF __key_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:166 */

/* BEGIN TYPEDEF __uint_least32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:57 */
#line 57 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint32_t __uint_least32_t;
/* END TYPEDEF __uint_least32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:57 */

/* BEGIN FUNCTION-DECL-EXTERN putchar LOC=/usr/include/stdio.h:618 VKEY=1258 */
#line 618 "/usr/include/stdio.h"
extern int putchar(int __c ) ;
/* END FUNCTION-DECL-EXTERN putchar LOC=/usr/include/stdio.h:618 VKEY=1258 */

/* BEGIN TYPEDEF __syscall_slong_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:197 */
#line 197 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __syscall_slong_t;
/* END TYPEDEF __syscall_slong_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:197 */

/* BEGIN TYPEDEF __quad_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:63 */
#line 63 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __quad_t;
/* END TYPEDEF __quad_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:63 */

/* BEGIN TYPEDEF __int_least16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:54 */
#line 54 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int16_t __int_least16_t;
/* END TYPEDEF __int_least16_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:54 */

/* BEGIN FUNCTION-DECL-EXTERN getc_unlocked LOC=/usr/include/stdio.h:589 VKEY=1239 */
#line 589 "/usr/include/stdio.h"
extern int ( __attribute__((__nonnull__(1))) getc_unlocked)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN getc_unlocked LOC=/usr/include/stdio.h:589 VKEY=1239 */

/* BEGIN STRUCT-DECL __anonstruct___mbstate_t_599531343 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 10 */
#line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
struct __anonstruct___mbstate_t_599531343 ;
/* END STRUCT-DECL __anonstruct___mbstate_t_599531343 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 10 */

/* BEGIN TYPEDEF __loff_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:203 */
#line 203 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __off64_t __loff_t;
/* END TYPEDEF __loff_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:203 */

/* BEGIN FUNCTION-DECL-EXTERN vsprintf LOC=/usr/include/stdio.h:380 VKEY=1118 */
#line 380 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int vsprintf(char * __restrict  __s , char const   * __restrict  __format ,
                                                  __gnuc_va_list __arg ) ;
/* END FUNCTION-DECL-EXTERN vsprintf LOC=/usr/include/stdio.h:380 VKEY=1118 */

/* BEGIN FUNCTION-DECL-EXTERN fgetc LOC=/usr/include/stdio.h:575 VKEY=1230 */
#line 575
extern int ( __attribute__((__nonnull__(1))) fgetc)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fgetc LOC=/usr/include/stdio.h:575 VKEY=1230 */

/* BEGIN FUNCTION-DECL-EXTERN fseeko LOC=/usr/include/stdio.h:803 VKEY=1380 */
#line 803
extern int ( __attribute__((__nonnull__(1))) fseeko)(FILE *__stream , __off_t __off ,
                                                     int __whence ) ;
/* END FUNCTION-DECL-EXTERN fseeko LOC=/usr/include/stdio.h:803 VKEY=1380 */

/* BEGIN STRUCT-DECL _IO_cookie_io_functions_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:55 18 */
#line 55 "/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h"
struct _IO_cookie_io_functions_t ;
/* END STRUCT-DECL _IO_cookie_io_functions_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:55 18 */

/* BEGIN FUNCTION-DECL-EXTERN fmemopen LOC=/usr/include/stdio.h:314 VKEY=1057 */
#line 314 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) FILE *( __attribute__((__leaf__)) fmemopen)(void *__s ,
                                                                                 size_t __len ,
                                                                                 char const   *__modes )  __attribute__((__malloc__(fclose,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN fmemopen LOC=/usr/include/stdio.h:314 VKEY=1057 */

/* BEGIN TYPEDEF __fsfilcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:189 */
#line 189 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsfilcnt64_t;
/* END TYPEDEF __fsfilcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:189 */

/* BEGIN TYPEDEF __int_least32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:56 */
#line 56 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int32_t __int_least32_t;
/* END TYPEDEF __int_least32_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:56 */

/* BEGIN FUNCTION-DECL-EXTERN remove LOC=/usr/include/stdio.h:158 VKEY=989 */
#line 158 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) remove)(char const   *__filename ) ;
/* END FUNCTION-DECL-EXTERN remove LOC=/usr/include/stdio.h:158 VKEY=989 */

/* BEGIN FUNCTION-DECL-EXTERN setvbuf LOC=/usr/include/stdio.h:339 VKEY=1076 */
#line 339
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) setvbuf)(FILE * __restrict  __stream ,
                                                                                              char * __restrict  __buf ,
                                                                                              int __modes ,
                                                                                              size_t __n ) ;
/* END FUNCTION-DECL-EXTERN setvbuf LOC=/usr/include/stdio.h:339 VKEY=1076 */

/* BEGIN FUNCTION-DECL-EXTERN fwrite LOC=/usr/include/stdio.h:745 VKEY=1342 */
#line 745
extern size_t ( __attribute__((__nonnull__(4))) fwrite)(void const   * __restrict  __ptr ,
                                                        size_t __size , size_t __n ,
                                                        FILE * __restrict  __s ) ;
/* END FUNCTION-DECL-EXTERN fwrite LOC=/usr/include/stdio.h:745 VKEY=1342 */

/* BEGIN FUNCTION-DECL-EXTERN renameat LOC=/usr/include/stdio.h:164 VKEY=1003 */
#line 164
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) renameat)(int __oldfd ,
                                                                               char const   *__old ,
                                                                               int __newfd ,
                                                                               char const   *__new ) ;
/* END FUNCTION-DECL-EXTERN renameat LOC=/usr/include/stdio.h:164 VKEY=1003 */

/* BEGIN FUNCTION-DECL-EXTERN fseek LOC=/usr/include/stdio.h:779 VKEY=1367 */
#line 779
extern int ( __attribute__((__nonnull__(1))) fseek)(FILE *__stream , long __off ,
                                                    int __whence ) ;
/* END FUNCTION-DECL-EXTERN fseek LOC=/usr/include/stdio.h:779 VKEY=1367 */

/* BEGIN TYPEDEF __int_least8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:52 */
#line 52 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __int8_t __int_least8_t;
/* END TYPEDEF __int_least8_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:52 */

/* BEGIN FUNCTION-DECL-EXTERN freopen LOC=/usr/include/stdio.h:271 VKEY=1038 */
#line 271 "/usr/include/stdio.h"
extern FILE *( __attribute__((__nonnull__(3))) freopen)(char const   * __restrict  __filename ,
                                                        char const   * __restrict  __modes ,
                                                        FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN freopen LOC=/usr/include/stdio.h:271 VKEY=1038 */

/* BEGIN STRUCT _G_fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 13 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h"
struct _G_fpos64_t {
   __off64_t __pos ;
   __mbstate_t __state ;
};
/* END STRUCT _G_fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 13 */

/* BEGIN TYPEDEF __fsfilcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:188 */
#line 188 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsfilcnt_t;
/* END TYPEDEF __fsfilcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:188 */

/* BEGIN FUNCTION-DECL-EXTERN ungetc LOC=/usr/include/stdio.h:731 VKEY=1324 */
#line 731 "/usr/include/stdio.h"
extern int ( __attribute__((__nonnull__(2))) ungetc)(int __c , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ungetc LOC=/usr/include/stdio.h:731 VKEY=1324 */

/* BEGIN FUNCTION-DECL-EXTERN putchar_unlocked LOC=/usr/include/stdio.h:636 VKEY=1271 */
#line 636
extern int putchar_unlocked(int __c ) ;
/* END FUNCTION-DECL-EXTERN putchar_unlocked LOC=/usr/include/stdio.h:636 VKEY=1271 */

/* BEGIN FUNCTION-DECL-EXTERN fputs LOC=/usr/include/stdio.h:717 VKEY=1316 */
#line 717
extern int ( __attribute__((__nonnull__(2))) fputs)(char const   * __restrict  __s ,
                                                    FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN fputs LOC=/usr/include/stdio.h:717 VKEY=1316 */

/* BEGIN FUNCTION-DECL-EXTERN rewind LOC=/usr/include/stdio.h:790 VKEY=1373 */
#line 790
extern void ( __attribute__((__nonnull__(1))) rewind)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN rewind LOC=/usr/include/stdio.h:790 VKEY=1373 */

/* BEGIN TYPEDEF __syscall_ulong_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:199 */
#line 199 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __syscall_ulong_t;
/* END TYPEDEF __syscall_ulong_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:199 */

/* BEGIN FUNCTION-DECL-EXTERN popen LOC=/usr/include/stdio.h:903 VKEY=1428 */
#line 903 "/usr/include/stdio.h"
extern FILE *popen(char const   *__command , char const   *__modes )  __attribute__((__malloc__(pclose,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN popen LOC=/usr/include/stdio.h:903 VKEY=1428 */

/* BEGIN FUNCTION-DECL-EXTERN fwrite_unlocked LOC=/usr/include/stdio.h:769 VKEY=1360 */
#line 769
extern size_t ( __attribute__((__nonnull__(4))) fwrite_unlocked)(void const   * __restrict  __ptr ,
                                                                 size_t __size , size_t __n ,
                                                                 FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN fwrite_unlocked LOC=/usr/include/stdio.h:769 VKEY=1360 */

/* BEGIN FUNCTION-DECL-EXTERN vfscanf LOC=/usr/include/stdio.h:490 VKEY=1196 */
#line 490
extern int ( /* format attribute */ __attribute__((__nonnull__(1))) vfscanf)(FILE * __restrict  __s ,
                                                                             char const   * __restrict  __format ,
                                                                             __gnuc_va_list __arg )  __asm__("__isoc99_vfscanf")  ;
/* END FUNCTION-DECL-EXTERN vfscanf LOC=/usr/include/stdio.h:490 VKEY=1196 */

/* BEGIN TYPEDEF __rlim_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:157 */
#line 157 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __rlim_t;
/* END TYPEDEF __rlim_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:157 */

/* BEGIN FUNCTION-DECL-EXTERN funlockfile LOC=/usr/include/stdio.h:948 VKEY=1440 */
#line 948 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) void ( __attribute__((__nonnull__(1), __leaf__)) funlockfile)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN funlockfile LOC=/usr/include/stdio.h:948 VKEY=1440 */

/* BEGIN TYPEDEF va_list LOC=/usr/include/stdio.h:53 */
#line 53 "/usr/include/stdio.h"
typedef __gnuc_va_list va_list;
/* END TYPEDEF va_list LOC=/usr/include/stdio.h:53 */

/* BEGIN TYPEDEF __id_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:159 */
#line 159 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __id_t;
/* END TYPEDEF __id_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:159 */

/* BEGIN FUNCTION-DECL-EXTERN perror LOC=/usr/include/stdio.h:878 VKEY=1414 */
#line 878 "/usr/include/stdio.h"
extern void perror(char const   *__s )  __attribute__((__cold__)) ;
/* END FUNCTION-DECL-EXTERN perror LOC=/usr/include/stdio.h:878 VKEY=1414 */

/* BEGIN FUNCTION-DECL-EXTERN rename LOC=/usr/include/stdio.h:160 VKEY=994 */
#line 160
extern  __attribute__((__nothrow__)) int ( __attribute__((__leaf__)) rename)(char const   *__old ,
                                                                             char const   *__new ) ;
/* END FUNCTION-DECL-EXTERN rename LOC=/usr/include/stdio.h:160 VKEY=994 */

/* BEGIN FUNCTION-DECL-EXTERN ferror LOC=/usr/include/stdio.h:864 VKEY=1402 */
#line 864
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) ferror)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ferror LOC=/usr/include/stdio.h:864 VKEY=1402 */

/* BEGIN FUNCTION-DECL-EXTERN fputc LOC=/usr/include/stdio.h:611 VKEY=1250 */
#line 611
extern int ( __attribute__((__nonnull__(2))) fputc)(int __c , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fputc LOC=/usr/include/stdio.h:611 VKEY=1250 */

/* BEGIN TYPEDEF __pid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:154 */
#line 154 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __pid_t;
/* END TYPEDEF __pid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:154 */

/* BEGIN TYPEDEF __uint_least64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:59 */
#line 59 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef __uint64_t __uint_least64_t;
/* END TYPEDEF __uint_least64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:59 */

/* BEGIN TYPEDEF __rlim64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:158 */
#line 158 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __rlim64_t;
/* END TYPEDEF __rlim64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:158 */

/* BEGIN FUNCTION-DECL-EXTERN __getdelim LOC=/usr/include/stdio.h:694 VKEY=1295 */
#line 694 "/usr/include/stdio.h"
extern __ssize_t ( __attribute__((__nonnull__(4))) __getdelim)(char ** __restrict  __lineptr ,
                                                               size_t * __restrict  __n ,
                                                               int __delimiter , FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN __getdelim LOC=/usr/include/stdio.h:694 VKEY=1295 */

/* BEGIN FUNCTION-DECL-EXTERN fdopen LOC=/usr/include/stdio.h:299 VKEY=1043 */
#line 299
extern  __attribute__((__nothrow__)) FILE *( __attribute__((__leaf__)) fdopen)(int __fd ,
                                                                               char const   *__modes )  __attribute__((__malloc__(fclose,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN fdopen LOC=/usr/include/stdio.h:299 VKEY=1043 */

/* BEGIN FUNCTION-DECL-EXTERN clearerr LOC=/usr/include/stdio.h:860 VKEY=1396 */
#line 860
extern  __attribute__((__nothrow__)) void ( __attribute__((__nonnull__(1), __leaf__)) clearerr)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN clearerr LOC=/usr/include/stdio.h:860 VKEY=1396 */

/* BEGIN FUNCTION-DECL-EXTERN ctermid LOC=/usr/include/stdio.h:911 VKEY=1431 */
#line 911
extern  __attribute__((__nothrow__)) char *( __attribute__((__leaf__)) ctermid)(char *__s )  __attribute__((__access__(__write_only__,1))) ;
/* END FUNCTION-DECL-EXTERN ctermid LOC=/usr/include/stdio.h:911 VKEY=1431 */

/* BEGIN FUNCTION-DECL-EXTERN vdprintf LOC=/usr/include/stdio.h:410 VKEY=1158 */
#line 410
extern int ( /* format attribute */  vdprintf)(int __fd , char const   * __restrict  __fmt ,
                                               __gnuc_va_list __arg ) ;
/* END FUNCTION-DECL-EXTERN vdprintf LOC=/usr/include/stdio.h:410 VKEY=1158 */

/* BEGIN TYPEDEF __ino64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:149 */
#line 149 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __ino64_t;
/* END TYPEDEF __ino64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:149 */

/* BEGIN TYPEDEF __useconds_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:161 */
#line 161 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __useconds_t;
/* END TYPEDEF __useconds_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:161 */

/* BEGIN FUNCTION-DECL-EXTERN vsscanf LOC=/usr/include/stdio.h:502 VKEY=1208 */
#line 502 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( /* format attribute */ __attribute__((__leaf__)) vsscanf)(char const   * __restrict  __s ,
                                                                                                     char const   * __restrict  __format ,
                                                                                                     __gnuc_va_list __arg )  __asm__("__isoc99_vsscanf")  ;
/* END FUNCTION-DECL-EXTERN vsscanf LOC=/usr/include/stdio.h:502 VKEY=1208 */

/* BEGIN TYPEDEF __timer_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:172 */
#line 172 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef void *__timer_t;
/* END TYPEDEF __timer_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:172 */

/* BEGIN FUNCTION-DECL-EXTERN setbuffer LOC=/usr/include/stdio.h:345 VKEY=1083 */
#line 345 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) void ( __attribute__((__nonnull__(1), __leaf__)) setbuffer)(FILE * __restrict  __stream ,
                                                                                                 char * __restrict  __buf ,
                                                                                                 size_t __size ) ;
/* END FUNCTION-DECL-EXTERN setbuffer LOC=/usr/include/stdio.h:345 VKEY=1083 */

/* BEGIN TYPEDEF __FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/__FILE.h:5 */
#line 5 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h"
typedef struct _IO_FILE __FILE;
/* END TYPEDEF __FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/__FILE.h:5 */

/* BEGIN FUNCTION-DECL-EXTERN ftell LOC=/usr/include/stdio.h:785 VKEY=1370 */
#line 785 "/usr/include/stdio.h"
extern long ( __attribute__((__nonnull__(1))) ftell)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ftell LOC=/usr/include/stdio.h:785 VKEY=1370 */

/* BEGIN TYPEDEF __dev_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:145 */
#line 145 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __dev_t;
/* END TYPEDEF __dev_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:145 */

/* BEGIN FUNCTION-DECL-EXTERN fscanf LOC=/usr/include/stdio.h:422 VKEY=1168 */
#line 422 "/usr/include/stdio.h"
extern int ( __attribute__((__nonnull__(1))) fscanf)(FILE * __restrict  __stream ,
                                                     char const   * __restrict  __format 
                                                     , ...)  __asm__("__isoc99_fscanf")  ;
/* END FUNCTION-DECL-EXTERN fscanf LOC=/usr/include/stdio.h:422 VKEY=1168 */

/* BEGIN TYPEDEF __sig_atomic_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:215 */
#line 215 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __sig_atomic_t;
/* END TYPEDEF __sig_atomic_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:215 */

/* BEGIN FUNCTION-DECL-EXTERN vprintf LOC=/usr/include/stdio.h:378 VKEY=1111 */
#line 378 "/usr/include/stdio.h"
extern int vprintf(char const   * __restrict  __format , __gnuc_va_list __arg ) ;
/* END FUNCTION-DECL-EXTERN vprintf LOC=/usr/include/stdio.h:378 VKEY=1111 */

/* BEGIN FUNCTION-DECL-EXTERN fgetpos LOC=/usr/include/stdio.h:829 VKEY=1388 */
#line 829
extern int ( __attribute__((__nonnull__(1))) fgetpos)(FILE * __restrict  __stream ,
                                                      fpos_t * __restrict  __pos ) ;
/* END FUNCTION-DECL-EXTERN fgetpos LOC=/usr/include/stdio.h:829 VKEY=1388 */

/* BEGIN TYPEDEF __fsblkcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:184 */
#line 184 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsblkcnt_t;
/* END TYPEDEF __fsblkcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:184 */

/* BEGIN VARIABLE-DECL-EXTERN stdout LOC=/usr/include/stdio.h:150 VKEY=985 */
#line 150 "/usr/include/stdio.h"
extern FILE *stdout ;
/* END VARIABLE-DECL-EXTERN stdout LOC=/usr/include/stdio.h:150 VKEY=985 */

/* BEGIN VARIABLE-DECL _TIG_IZ_eB00_argv LOC=UNKNOWN VKEY=1466 */
char **_TIG_IZ_eB00_argv ;
/* END VARIABLE-DECL _TIG_IZ_eB00_argv LOC=UNKNOWN VKEY=1466 */

/* BEGIN FUNCTION-DECL-EXTERN setlinebuf LOC=/usr/include/stdio.h:349 VKEY=1086 */
#line 349
extern  __attribute__((__nothrow__)) void ( __attribute__((__nonnull__(1), __leaf__)) setlinebuf)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN setlinebuf LOC=/usr/include/stdio.h:349 VKEY=1086 */

/* BEGIN TYPEDEF __fsblkcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:185 */
#line 185 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __fsblkcnt64_t;
/* END TYPEDEF __fsblkcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:185 */

/* BEGIN TYPEDEF __blkcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:181 */
#line 181 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blkcnt64_t;
/* END TYPEDEF __blkcnt64_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:181 */

/* BEGIN TYPEDEF __nlink_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:151 */
#line 151 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __nlink_t;
/* END TYPEDEF __nlink_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:151 */

/* BEGIN FUNCTION-DECL-EXTERN putw LOC=/usr/include/stdio.h:646 VKEY=1279 */
#line 646 "/usr/include/stdio.h"
extern int ( __attribute__((__nonnull__(2))) putw)(int __w , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN putw LOC=/usr/include/stdio.h:646 VKEY=1279 */

/* BEGIN FUNCTION-DECL-EXTERN fputc_unlocked LOC=/usr/include/stdio.h:627 VKEY=1263 */
#line 627
extern int ( __attribute__((__nonnull__(2))) fputc_unlocked)(int __c , FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fputc_unlocked LOC=/usr/include/stdio.h:627 VKEY=1263 */

/* BEGIN FUNCTION-DECL-EXTERN fprintf LOC=/usr/include/stdio.h:357 VKEY=1091 */
#line 357
extern int ( __attribute__((__nonnull__(1))) fprintf)(FILE * __restrict  __stream ,
                                                      char const   * __restrict  __format 
                                                      , ...) ;
/* END FUNCTION-DECL-EXTERN fprintf LOC=/usr/include/stdio.h:357 VKEY=1091 */

/* BEGIN FUNCTION-DECL-EXTERN fflush LOC=/usr/include/stdio.h:236 VKEY=1023 */
#line 236
extern int fflush(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fflush LOC=/usr/include/stdio.h:236 VKEY=1023 */

/* BEGIN FUNCTION-DECL-EXTERN ftrylockfile LOC=/usr/include/stdio.h:945 VKEY=1437 */
#line 945
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) ftrylockfile)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ftrylockfile LOC=/usr/include/stdio.h:945 VKEY=1437 */

/* BEGIN FUNCTION-DECL-EXTERN vscanf LOC=/usr/include/stdio.h:498 VKEY=1201 */
#line 498
extern int ( /* format attribute */  vscanf)(char const   * __restrict  __format ,
                                             __gnuc_va_list __arg )  __asm__("__isoc99_vscanf")  ;
/* END FUNCTION-DECL-EXTERN vscanf LOC=/usr/include/stdio.h:498 VKEY=1201 */

/* BEGIN STRUCT-DECL _IO_marker LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:36 15 */
#line 36 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_marker ;
/* END STRUCT-DECL _IO_marker LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:36 15 */

/* BEGIN TYPEDEF __uid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:146 */
#line 146 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __uid_t;
/* END TYPEDEF __uid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:146 */

/* BEGIN STRUCT-DECL _G_fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 12 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h"
struct _G_fpos_t ;
/* END STRUCT-DECL _G_fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 12 */

/* BEGIN STRUCT _IO_FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:49 14 */
#line 49 "/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h"
struct _IO_FILE {
   int _flags ;
   char *_IO_read_ptr ;
   char *_IO_read_end ;
   char *_IO_read_base ;
   char *_IO_write_base ;
   char *_IO_write_ptr ;
   char *_IO_write_end ;
   char *_IO_buf_base ;
   char *_IO_buf_end ;
   char *_IO_save_base ;
   char *_IO_backup_base ;
   char *_IO_save_end ;
   struct _IO_marker *_markers ;
   struct _IO_FILE *_chain ;
   int _fileno ;
   int _flags2 ;
   __off_t _old_offset ;
   unsigned short _cur_column ;
   signed char _vtable_offset ;
   char _shortbuf[1] ;
   _IO_lock_t *_lock ;
   __off64_t _offset ;
   struct _IO_codecvt *_codecvt ;
   struct _IO_wide_data *_wide_data ;
   struct _IO_FILE *_freeres_list ;
   void *_freeres_buf ;
   size_t __pad5 ;
   int _mode ;
   char _unused2[(15UL * sizeof(int ) - 4UL * sizeof(void *)) - sizeof(size_t )] ;
};
/* END STRUCT _IO_FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/struct_FILE.h:49 14 */

/* BEGIN FUNCTION-DECL-EXTERN getc LOC=/usr/include/stdio.h:576 VKEY=1233 */
#line 576 "/usr/include/stdio.h"
extern int ( __attribute__((__nonnull__(1))) getc)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN getc LOC=/usr/include/stdio.h:576 VKEY=1233 */

/* BEGIN STRUCT _IO_cookie_io_functions_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:55 18 */
#line 55 "/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h"
struct _IO_cookie_io_functions_t {
   cookie_read_function_t *read ;
   cookie_write_function_t *write ;
   cookie_seek_function_t *seek ;
   cookie_close_function_t *close ;
};
/* END STRUCT _IO_cookie_io_functions_t LOC=/usr/include/x86_64-linux-gnu/bits/types/cookie_io_functions_t.h:55 18 */

/* BEGIN FUNCTION-DECL-EXTERN fileno_unlocked LOC=/usr/include/stdio.h:888 VKEY=1420 */
#line 888 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) fileno_unlocked)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fileno_unlocked LOC=/usr/include/stdio.h:888 VKEY=1420 */

/* BEGIN TYPEDEF __fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h"
typedef struct _G_fpos64_t __fpos64_t;
/* END TYPEDEF __fpos64_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos64_t.h:10 */

/* BEGIN FUNCTION-DECL-EXTERN getw LOC=/usr/include/stdio.h:643 VKEY=1274 */
#line 643 "/usr/include/stdio.h"
extern int ( __attribute__((__nonnull__(1))) getw)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN getw LOC=/usr/include/stdio.h:643 VKEY=1274 */

/* BEGIN TYPEDEF __blkcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:180 */
#line 180 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __blkcnt_t;
/* END TYPEDEF __blkcnt_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:180 */

/* BEGIN UNION-DECL __anonunion___value_751190509 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 CKEY=11 */
#line 13 "/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h"
union __anonunion___value_751190509 ;
/* END UNION-DECL __anonunion___value_751190509 LOC=/usr/include/x86_64-linux-gnu/bits/types/__mbstate_t.h:13 CKEY=11 */

/* BEGIN FUNCTION-DECL-EXTERN scanf LOC=/usr/include/stdio.h:428 VKEY=1171 */
#line 428 "/usr/include/stdio.h"
extern int scanf(char const   * __restrict  __format  , ...)  __asm__("__isoc99_scanf")  ;
/* END FUNCTION-DECL-EXTERN scanf LOC=/usr/include/stdio.h:428 VKEY=1171 */

/* BEGIN FUNCTION-DECL-EXTERN puts LOC=/usr/include/stdio.h:724 VKEY=1319 */
#line 724
extern int puts(char const   *__s ) ;
/* END FUNCTION-DECL-EXTERN puts LOC=/usr/include/stdio.h:724 VKEY=1319 */

/* BEGIN VARIABLE-DEF _TIG_IZ_eB00_argc LOC=UNKNOWN VKEY=1465 */
int _TIG_IZ_eB00_argc  ;
/* END VARIABLE-DEF _TIG_IZ_eB00_argc LOC=UNKNOWN VKEY=1465 */

/* BEGIN TYPEDEF __u_int LOC=/usr/include/x86_64-linux-gnu/bits/types.h:33 */
#line 33 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned int __u_int;
/* END TYPEDEF __u_int LOC=/usr/include/x86_64-linux-gnu/bits/types.h:33 */

/* BEGIN FUNCTION-DECL-EXTERN getchar LOC=/usr/include/stdio.h:582 VKEY=1236 */
#line 582 "/usr/include/stdio.h"
extern int getchar(void) ;
/* END FUNCTION-DECL-EXTERN getchar LOC=/usr/include/stdio.h:582 VKEY=1236 */

/* BEGIN FUNCTION-DECL-EXTERN dprintf LOC=/usr/include/stdio.h:413 VKEY=1163 */
#line 413
extern int ( /* format attribute */  dprintf)(int __fd , char const   * __restrict  __fmt 
                                              , ...) ;
/* END FUNCTION-DECL-EXTERN dprintf LOC=/usr/include/stdio.h:413 VKEY=1163 */

/* BEGIN FUNCTION-DECL-EXTERN setbuf LOC=/usr/include/stdio.h:334 VKEY=1067 */
#line 334
extern  __attribute__((__nothrow__)) void ( __attribute__((__nonnull__(1), __leaf__)) setbuf)(FILE * __restrict  __stream ,
                                                                                              char * __restrict  __buf ) ;
/* END FUNCTION-DECL-EXTERN setbuf LOC=/usr/include/stdio.h:334 VKEY=1067 */

/* BEGIN FUNCTION-DECL-EXTERN asprintf LOC=/usr/include/stdio.h:403 VKEY=1151 */
#line 403
extern  __attribute__((__nothrow__)) int ( /* format attribute */  asprintf)(char ** __restrict  __ptr ,
                                                                             char const   * __restrict  __fmt 
                                                                             , ...) ;
/* END FUNCTION-DECL-EXTERN asprintf LOC=/usr/include/stdio.h:403 VKEY=1151 */

/* BEGIN FUNCTION-DECL-EXTERN fileno LOC=/usr/include/stdio.h:883 VKEY=1417 */
#line 883
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) fileno)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fileno LOC=/usr/include/stdio.h:883 VKEY=1417 */

/* BEGIN STRUCT _G_fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 12 */
#line 10 "/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h"
struct _G_fpos_t {
   __off_t __pos ;
   __mbstate_t __state ;
};
/* END STRUCT _G_fpos_t LOC=/usr/include/x86_64-linux-gnu/bits/types/__fpos_t.h:10 12 */

/* BEGIN TYPEDEF __intptr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:207 */
#line 207 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __intptr_t;
/* END TYPEDEF __intptr_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:207 */

/* BEGIN FUNCTION-DECL-EXTERN tmpnam_r LOC=/usr/include/stdio.h:216 VKEY=1015 */
#line 216 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__leaf__)) tmpnam_r)(char *__s ) ;
/* END FUNCTION-DECL-EXTERN tmpnam_r LOC=/usr/include/stdio.h:216 VKEY=1015 */

/* BEGIN FUNCTION-DECL-EXTERN __asprintf LOC=/usr/include/stdio.h:400 VKEY=1146 */
#line 400
extern  __attribute__((__nothrow__)) int ( /* format attribute */  __asprintf)(char ** __restrict  __ptr ,
                                                                               char const   * __restrict  __fmt 
                                                                               , ...) ;
/* END FUNCTION-DECL-EXTERN __asprintf LOC=/usr/include/stdio.h:400 VKEY=1146 */

/* BEGIN FUNCTION-DECL-EXTERN flockfile LOC=/usr/include/stdio.h:941 VKEY=1434 */
#line 941
extern  __attribute__((__nothrow__)) void ( __attribute__((__nonnull__(1), __leaf__)) flockfile)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN flockfile LOC=/usr/include/stdio.h:941 VKEY=1434 */

/* BEGIN FUNCTION-DECL-EXTERN __overflow LOC=/usr/include/stdio.h:960 VKEY=1448 */
#line 960
extern int __overflow(FILE * , int  ) ;
/* END FUNCTION-DECL-EXTERN __overflow LOC=/usr/include/stdio.h:960 VKEY=1448 */

/* BEGIN STRUCT-DECL _IO_FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/__FILE.h:4 14 */
#line 4 "/usr/include/x86_64-linux-gnu/bits/types/__FILE.h"
struct _IO_FILE ;
/* END STRUCT-DECL _IO_FILE LOC=/usr/include/x86_64-linux-gnu/bits/types/__FILE.h:4 14 */

/* BEGIN TYPEDEF __suseconds_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:162 */
#line 162 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __suseconds_t;
/* END TYPEDEF __suseconds_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:162 */

/* BEGIN STRUCT __anonstruct___fsid_t_109580352 LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 9 */
#line 155 "/usr/include/x86_64-linux-gnu/bits/types.h"
struct __anonstruct___fsid_t_109580352 {
   int __val[2] ;
};
/* END STRUCT __anonstruct___fsid_t_109580352 LOC=/usr/include/x86_64-linux-gnu/bits/types.h:155 9 */

/* BEGIN FUNCTION-DECL-EXTERN fflush_unlocked LOC=/usr/include/stdio.h:245 VKEY=1026 */
#line 245 "/usr/include/stdio.h"
extern int fflush_unlocked(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fflush_unlocked LOC=/usr/include/stdio.h:245 VKEY=1026 */

/* BEGIN FUNCTION-DECL-EXTERN fopen LOC=/usr/include/stdio.h:264 VKEY=1031 */
#line 264
extern FILE *fopen(char const   * __restrict  __filename , char const   * __restrict  __modes )  __attribute__((__malloc__(fclose,1),
__malloc__)) ;
/* END FUNCTION-DECL-EXTERN fopen LOC=/usr/include/stdio.h:264 VKEY=1031 */

/* BEGIN FUNCTION-DECL-EXTERN ferror_unlocked LOC=/usr/include/stdio.h:870 VKEY=1411 */
#line 870
extern  __attribute__((__nothrow__)) int ( __attribute__((__nonnull__(1), __leaf__)) ferror_unlocked)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ferror_unlocked LOC=/usr/include/stdio.h:870 VKEY=1411 */

/* BEGIN FUNCTION-DECL-EXTERN getline LOC=/usr/include/stdio.h:707 VKEY=1311 */
#line 707
extern __ssize_t ( __attribute__((__nonnull__(3))) getline)(char ** __restrict  __lineptr ,
                                                            size_t * __restrict  __n ,
                                                            FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN getline LOC=/usr/include/stdio.h:707 VKEY=1311 */

/* BEGIN FUNCTION-DECL-EXTERN getdelim LOC=/usr/include/stdio.h:697 VKEY=1304 */
#line 697
extern __ssize_t ( __attribute__((__nonnull__(4))) getdelim)(char ** __restrict  __lineptr ,
                                                             size_t * __restrict  __n ,
                                                             int __delimiter , FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN getdelim LOC=/usr/include/stdio.h:697 VKEY=1304 */

/* BEGIN TYPEDEF __clockid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:169 */
#line 169 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef int __clockid_t;
/* END TYPEDEF __clockid_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:169 */

/* BEGIN FUNCTION-DECL-EXTERN tmpnam LOC=/usr/include/stdio.h:211 VKEY=1012 */
#line 211 "/usr/include/stdio.h"
extern  __attribute__((__nothrow__)) char *( __attribute__((__leaf__)) tmpnam)(char * ) ;
/* END FUNCTION-DECL-EXTERN tmpnam LOC=/usr/include/stdio.h:211 VKEY=1012 */

/* BEGIN FUNCTION-DECL main LOC=UNKNOWN VKEY=1475 */
int main(int argc , char **argv , char **_TIG_IZ_eB00_formal_envp ) ;
/* END FUNCTION-DECL main LOC=UNKNOWN VKEY=1475 */

/* BEGIN FUNCTION-DECL-EXTERN sprintf LOC=/usr/include/stdio.h:365 VKEY=1099 */
#line 365
extern  __attribute__((__nothrow__)) int sprintf(char * __restrict  __s , char const   * __restrict  __format 
                                                 , ...) ;
/* END FUNCTION-DECL-EXTERN sprintf LOC=/usr/include/stdio.h:365 VKEY=1099 */

/* BEGIN TYPEDEF __u_char LOC=/usr/include/x86_64-linux-gnu/bits/types.h:31 */
#line 31 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned char __u_char;
/* END TYPEDEF __u_char LOC=/usr/include/x86_64-linux-gnu/bits/types.h:31 */

/* BEGIN FUNCTION-DECL-EXTERN fread LOC=/usr/include/stdio.h:738 VKEY=1333 */
#line 738 "/usr/include/stdio.h"
extern size_t ( __attribute__((__nonnull__(4))) fread)(void * __restrict  __ptr ,
                                                       size_t __size , size_t __n ,
                                                       FILE * __restrict  __stream ) ;
/* END FUNCTION-DECL-EXTERN fread LOC=/usr/include/stdio.h:738 VKEY=1333 */

/* BEGIN TYPEDEF __u_quad_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:64 */
#line 64 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef unsigned long __u_quad_t;
/* END TYPEDEF __u_quad_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:64 */

/* BEGIN TYPEDEF __intmax_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:72 */
#line 72 "/usr/include/x86_64-linux-gnu/bits/types.h"
typedef long __intmax_t;
/* END TYPEDEF __intmax_t LOC=/usr/include/x86_64-linux-gnu/bits/types.h:72 */

/* BEGIN FUNCTION-DECL-EXTERN ftello LOC=/usr/include/stdio.h:809 VKEY=1383 */
#line 809 "/usr/include/stdio.h"
extern __off_t ( __attribute__((__nonnull__(1))) ftello)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN ftello LOC=/usr/include/stdio.h:809 VKEY=1383 */

/* BEGIN FUNCTION-DECL-EXTERN fgets LOC=/usr/include/stdio.h:654 VKEY=1286 */
#line 654
extern char *( __attribute__((__nonnull__(3))) fgets)(char * __restrict  __s , int __n ,
                                                      FILE * __restrict  __stream )  __attribute__((__access__(__write_only__,1,2))) ;
/* END FUNCTION-DECL-EXTERN fgets LOC=/usr/include/stdio.h:654 VKEY=1286 */

/* BEGIN FUNCTION-DECL-EXTERN fgetc_unlocked LOC=/usr/include/stdio.h:600 VKEY=1245 */
#line 600
extern int ( __attribute__((__nonnull__(1))) fgetc_unlocked)(FILE *__stream ) ;
/* END FUNCTION-DECL-EXTERN fgetc_unlocked LOC=/usr/include/stdio.h:600 VKEY=1245 */

/* BEGIN FUNCTION-DEF main LOC=UNKNOWN VKEY=1475 */
int main(int argc , char **argv , char **_TIG_IZ_eB00_formal_envp ) 
{ 
  int temp ;
  int i ;
  int j ;
  int a[10] ;
  unsigned long _TIG_FN_eB00_1_main_next ;

  {
  {
  {
  {
  {
  _TIG_IZ_eB00_argc = 0;
  goto _TIG_IZ_eB00_argc__INITINLINE__TIG_IZ_eB00_argc__INIT;
  }
  _TIG_IZ_eB00_argc__INITINLINE__TIG_IZ_eB00_argc__INIT: /* CIL Label */ ;
  }
  {
  {
  _TIG_IZ_eB00_argv = (char **)0;
  goto _TIG_IZ_eB00_argv__INITINLINE__TIG_IZ_eB00_argv__INIT;
  }
  _TIG_IZ_eB00_argv__INITINLINE__TIG_IZ_eB00_argv__INIT: /* CIL Label */ ;
  }
  {
  {
  _TIG_IZ_eB00_envp = (char **)0;
  goto _TIG_IZ_eB00_envp__INITINLINE__TIG_IZ_eB00_envp__INIT;
  }
  _TIG_IZ_eB00_envp__INITINLINE__TIG_IZ_eB00_envp__INIT: /* CIL Label */ ;
  }
  goto megaInitINLINE_megaInit;
  }
  megaInitINLINE_megaInit: /* CIL Label */ ;
  }
  while (1) {
    __asm__ volatile ("##_ANNOTATION_INITIALREGION_-TIG-IZ-eB00--0":);
    _TIG_IZ_eB00_argc = argc;
    _TIG_IZ_eB00_argv = argv;
    _TIG_IZ_eB00_envp = _TIG_IZ_eB00_formal_envp;
    break;
  }
  {
  _TIG_FN_eB00_1_main_next = 22UL;
  }
  while (1) {
    switch (_TIG_FN_eB00_1_main_next) {
    case 25UL: 
#line 16 "bubblesort.c"
    j ++;
    {
    _TIG_FN_eB00_1_main_next = 15UL;
    }
    break;
    case 15UL: ;
    if (j <= i) {
      {
      _TIG_FN_eB00_1_main_next = 16UL;
      }
    } else {
      {
      _TIG_FN_eB00_1_main_next = 21UL;
      }
    }
    break;
    case 12UL: 
#line 25
    printf((char const   */* __restrict  */)"After sorting: ");
#line 26
    i = 0;
    {
    _TIG_FN_eB00_1_main_next = 5UL;
    }
    break;
    case 8UL: 
#line 16
    j = 0;
    {
    _TIG_FN_eB00_1_main_next = 15UL;
    }
    break;
    case 1UL: ;
    if (i < argc) {
      {
      _TIG_FN_eB00_1_main_next = 2UL;
      }
    } else {
      {
      _TIG_FN_eB00_1_main_next = 20UL;
      }
    }
    break;
    case 23UL: ;
    return (0);
    break;
    case 16UL: ;
    if (a[j] > a[j + 1]) {
      {
      _TIG_FN_eB00_1_main_next = 10UL;
      }
    } else {
      {
      _TIG_FN_eB00_1_main_next = 25UL;
      }
    }
    break;
    case 24UL: 
#line 27
    printf((char const   */* __restrict  */)" %d", a[i]);
#line 26
    i ++;
    {
    _TIG_FN_eB00_1_main_next = 5UL;
    }
    break;
    case 21UL: 
#line 15
    i --;
    {
    _TIG_FN_eB00_1_main_next = 13UL;
    }
    break;
    case 13UL: ;
    if (i >= 0) {
      {
      _TIG_FN_eB00_1_main_next = 8UL;
      }
    } else {
      {
      _TIG_FN_eB00_1_main_next = 12UL;
      }
    }
    break;
    case 22UL: 
#line 10
    i = 1;
    {
    _TIG_FN_eB00_1_main_next = 1UL;
    }
    break;
    case 5UL: ;
    if (i < argc - 1) {
      {
      _TIG_FN_eB00_1_main_next = 24UL;
      }
    } else {
      {
      _TIG_FN_eB00_1_main_next = 23UL;
      }
    }
    break;
    case 10UL: 
#line 18
    temp = a[j];
#line 19
    a[j] = a[j + 1];
#line 20
    a[j + 1] = temp;
    {
    _TIG_FN_eB00_1_main_next = 25UL;
    }
    break;
    case 2UL: 
#line 11
    a[i - 1] = (int )*(*(argv + i) + 0);
#line 10
    i ++;
    {
    _TIG_FN_eB00_1_main_next = 1UL;
    }
    break;
    case 20UL: 
#line 15
    i = argc - 3;
    {
    _TIG_FN_eB00_1_main_next = 13UL;
    }
    break;
    default: 
    break;
    }
  }
}
}
/* END FUNCTION-DEF main LOC=UNKNOWN VKEY=1475 */
